### ISSUE TITLE
HephaestusPlus disable tool durability and upgrade

### ISSUE THREAD

**Issue by tp1454** [KonSola5/HephaestusPlus#1]
Minecraft Version
1.20.1

Quilt Version
0.22.0-beta.1

Quilt Fabric API Version
7.4.0+0.90.0+1.20.1

Hephaestus Version
1.20.1-3.6.3.240

Describe your issue
using HephaestusPlus disable tool durability and upgrade
![Ảnh chụp màn hình 2023-11-28 081229](https://github.com/KonSola5/HephaestusPlus/assets/88155364/a9a8c063-2b8d-4425-b060-ecae49ae4d3b)
![Ảnh chụp màn hình 2023-11-28 082058](https://github.com/KonSola5/HephaestusPlus/assets/88155364/494797f8-04d8-451a-9a9c-6f21c00acf85)

Crash Report

Other mods
[mods.md](https://github.com/KonSola5/HephaestusPlus/files/13482404/mods.md)

Tried reproducing with just Tinkers?
No

Performance Enchancers
Sodium, Other (specify under other mods)

Searched for known issues?
Checked pinned issues, Searched open issues, Searched closed issues

**Comment by KonSola5** [comment]
Hmm, if that's the case then tags are messed up.
(Probably didn't notice this when testing whether the addon will work without FabricaeExNihilo).

**Comment by KonSola5** [comment]
Fixed by [this commit](https://github.com/KonSola5/HephaestusPlus/commit/46e8cd3301c8fac1f291b48d9dd082d99c0f72fd).
Marked the Crook/Hand Hammer tags as not required, so the tag still loads if those are missing.
A hotfix will be posted shortly after.
