### ISSUE TITLE
[Feature] Mythic Metals equipment should be meltable in Smelteries/Foundries like vanilla equipment.

### ISSUE THREAD

**Issue by Mieridduryn** [KonSola5/HephaestusPlus#11]
You can melt down vanilla equipment. You can melt down MM metals. Why not allow the melting of MM equipment?

**Comment by KonSola5** [comment]
It's a matter of adding recipes - I was just too lazy to add them.

**Comment by KonSola5** [comment]
Added a plethora of new melting recipes - I tackled tools/armor that need upgrades in such a way that it returns meltable materials needed for the pattern duplication recipe (only when Foundry is used).
