### ISSUE TITLE
[Feature] Tinkers' Tool Leveling Functionality for HephPlus?

### ISSUE THREAD

**Issue by Mieridduryn** [KonSola5/HephaestusPlus#15]
Hephaestus, being a port of Tinkers' Construct and TConstruct alone, doesn't include with it the features of a mod I see included with it in a lot of modpacks: [Tinkers' Tool Leveling](https://www.curseforge.com/minecraft/mc-mods/tinkers-tool-leveling).

It would be awesome if HephPlus could implement something similar to this, where one can level up their tools for more modifier slots.

This may not be within HephPlus' scope, and if it isn't, sorry for wasting your time.

**Comment by KonSola5** [comment]
Tool leveling won't be implemented in HephaestusPlus.
The whole idea of TiC3/Hephaestus is that you have limited modifier/ability slots, so you can't just throw everything on your tool - this encourages building multiple tools dedicated to the certain action.

If I (or someone else) would ever port Tinker's Leveling Addon (the TiC3 version of Tool Leveling) to Hephaestus, it would be a separate mod, completely detatched from HephaestusPlus.

**Comment by Mieridduryn** [comment]
Completely valid, have a nice day.

**Comment by unilock** [comment]
I ported Tinkers' Tool Leveling to Hephaestus a while ago, if anyone's still interested: https://github.com/unilock/HephaestusLeveling
