### ISSUE TITLE
Hephaestus plus causing blank patterns to not be able to be put into correct slot of part buolder

### ISSUE THREAD

**Issue by KorruptDragon** [KonSola5/HephaestusPlus#2]
Hephaestus has a part builder where when you put in a blank pattern into the left hand slot it allows you to use items like flint, cobble stone, wood, etc… to build certain tool parts. When Hephaestus plus is installed it stops the ability to put the blank pattern into the left hand slot. 

To reproduce use fabric 0.14.25 on 1.20.1 and install Hephaestus plus version 1.1.0 and Hephaestus, then create a world and get a parts builder and a blank pattern. Try to put the blank pattern into the left hand slot. It will not be able to be inserted. 

No crash was caused

**Comment by Nikolass1000** [comment]
Same here, pattern can't be put into `container.1` of part builder unless forced by command

**Comment by KonSola5** [comment]
Most likely the 'tconstruct:patterns' tag borked up since this mod adds a Crook Head pattern (casts), which weren't tagged as optional, thus tag loading fails if FabricaeExNihilo is not present.

Temporarily, you can install https://www.curseforge.com/minecraft/mc-mods/lmft to remedy this problem.

**Comment by KonSola5** [comment]
Finally managed to write a proper tag generator, so now all optional things are truly optional.
(As a bonus, also reduced the amount of exceptions thrown when FabricaeExNihilo is not present).
