### ISSUE TITLE
Botania Not Detected by Mod

### ISSUE THREAD

**Issue by Lilwhiteshark** [KonSola5/HephaestusPlus#3]
## **Describe the bug**
HephaestusPlus does not detect Botania, and does not add any of its additional materials or modifiers when Botania is installed.

## **To Reproduce**
1. Start the game with the following mods installed:
**Botania**
**Hephaestus**
**HephaestusPlus** 

2. Launch a world (the following warning message is outputted by HephaestusPlus on world load)
"! Neither FabricaeExNihilo nor Mythic Metals were detected! 
Currently HephaestusPlus does not add any additions to the base Hephaestus."

## **Expected behavior**
HephaestusPlus detects Botania on load, and adds its materials and modifiers to the game.

## **Screenshots**
![HephaestusPlus Warn Message](https://github.com/KonSola5/HephaestusPlus/assets/79448979/a47f8064-aa18-4b95-8c5c-6e0ea435bdde)
![HephaestusPlus EMI Search](https://github.com/KonSola5/HephaestusPlus/assets/79448979/0436e802-f03e-4566-816e-1dd8a1e80d10)

## **Crash log or game log (if applicable)**
[latest.log](https://gist.github.com/Lilwhiteshark/44d478f3afd487c0e70dadd455ad65ef)

## **Versions**
- Loader: [Fabric]
- Hephaestus: `1.20.1-3.6.3.240`
- HephaestusPlus: `1.1.0+1.20`
- Botania: `1.20.1-443-FABRIC`

## **Additional context**
The second screenshot is of an EMI search using the mod ID `hephaestusplus`. The displayed items are the only ones registered by the mod, and have none of the repair kits from Botania materials.

Botania is registered and playable in the instance with no issues, it just seems to be undetected by HephaestusPlus.

**Comment by KonSola5** [comment]
This is because of an oversight - didn't specify Botania in the code for displaying the warning.

**Comment by Lilwhiteshark** [comment]
Gotcha, and upon looking a little more I see that the materials are added under the `tconstruct` mod ID, my mistake!

**Comment by KonSola5** [comment]
This was already fixed in the commit c0392d6, though the fix wasn't published to CurseForge/Modrinth.
Now it is.
