### ISSUE TITLE
Missing casts tags

### ISSUE THREAD

**Issue by tiigerbones** [KonSola5/HephaestusPlus#9]
## **Describe the bug**
When attempting to pour into a cast (crook) nothing happens. Due to missing tags in the datagen
multi_use
and
single_use for each cast

## **To Reproduce**
Make a crook cast and try to pour any metal into it.

## **Expected behavior**
For a crook part to be created

## **Screenshots**

https://github.com/KonSola5/HephaestusPlus/assets/101901291/f862764b-c3a5-4c29-9fbe-212e70fc7fe4

## **Mod List**
Just the core mods for Hephaestus and HephaestusPlus (in this case Fabricae Ex Nihilo)
<details>
<summary>Mod List: click to show</summary>
<ul>
<li> An entry
</ul>
</details>

## **Versions**
- Loader: Fabric
- Hephaestus: 1.20.1-3.6.4.271
- HephaestusPlus: 1.1.1+1.20
- Other (if necessary):

## **Additional context**
Manually creating the missing files fixes the issue

**Comment by KonSola5** [comment]
Fixed!
![2024-04-29_13 29 19](https://github.com/KonSola5/HephaestusPlus/assets/125081901/b583fab8-5ebc-4e48-8db1-7b5ab75999db)
